"""
distributor.py — Main Distribution Orchestrator
Motto Appraisal Service | Content Distribution Pipeline

Full distribution pipeline for one piece of LinkedIn content:
  1. Classify
  2. Transform to all platform variants (via Claude)
  3. Queue X posts for auto-posting (if AUTO_POST_X=true)
  4. Queue Beehiiv draft (always draft, never auto-sent)
  5. Add Reddit/Facebook group versions to manual review queue
  6. Post rephrased version to company page (if POST_TO_COMPANY_PAGE=true)
  7. Queue community content (Reddit subreddits, LinkedIn groups, Facebook groups)
  8. Log everything to /home/user/workspace/cron_tracking/distribution_log.md

Usage:
    from agent.distributor import distribute

    result = distribute(post_data, auto_post_x=False)
"""

from __future__ import annotations

import json
import os
import sys
import time
import traceback
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Path setup — ensure project root is importable
# ---------------------------------------------------------------------------

_PROJECT_ROOT = Path(__file__).parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from tools.classifier import classify
from tools.transformer import transform
from tools.queue import (
    add_to_queue,
    mark_posted,
    mark_failed,
    mark_skipped,
    get_stats,
)
from tools.x_poster import safe_post_tweet, safe_post_thread, is_auto_post_enabled
from tools.beehiiv_publisher import create_post, markdown_to_html
from tools.linkedin_company import post_to_company_page, rephrase_for_brand
from tools.reddit_poster import queue_for_subreddits
from tools.linkedin_groups import queue_for_groups
from tools.facebook_groups import queue_for_manual_review as queue_fb_groups

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

LOG_PATH = Path("/home/user/workspace/cron_tracking/distribution_log.md")
QUEUE_PATH = Path("/home/user/workspace/cron_tracking/distribution_queue.json")
RESULTS_DIR = Path("/home/user/workspace/cron_tracking/results")


# ---------------------------------------------------------------------------
# Logging helpers
# ---------------------------------------------------------------------------

def _now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def _log(message: str) -> None:
    """Append a timestamped log line to distribution_log.md."""
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with LOG_PATH.open("a") as f:
        f.write(f"{message}\n")


def _log_section(title: str) -> None:
    _log(f"\n### {title}")


def _log_entry(label: str, value: str) -> None:
    _log(f"- **{label}**: {value}")


def _init_log_run(post_urn: str, pillar: int) -> None:
    """Write run header to log."""
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not LOG_PATH.exists():
        with LOG_PATH.open("w") as f:
            f.write("# Motto Appraisal — Content Distribution Log\n\n")
            f.write("_Auto-generated by distributor.py_\n\n")
            f.write("---\n\n")

    _log(f"\n## Run: {_now()}")
    _log(f"**Post URN**: `{post_urn}`  ")
    _log(f"**Pillar**: {pillar}  ")
    _log("")


# ---------------------------------------------------------------------------
# Results persistence
# ---------------------------------------------------------------------------

def _save_results(post_urn: str, results: dict) -> Path:
    """Save full transform + distribution results to a JSON file."""
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    safe_urn = post_urn.replace(":", "_").replace("/", "_")
    timestamp = time.strftime("%Y%m%d_%H%M%S", time.gmtime())
    filename = f"result_{safe_urn}_{timestamp}.json"
    path = RESULTS_DIR / filename
    with path.open("w") as f:
        json.dump(results, f, indent=2)
    return path


# ---------------------------------------------------------------------------
# Platform queueing helpers
# ---------------------------------------------------------------------------

def _queue_x_posts(
    post_urn: str,
    x_posts: list[str],
    x_thread: list[str],
    auto_post_x: bool,
    transform_output: dict,
) -> dict:
    """
    Queue X posts and optionally auto-post if enabled.

    Returns:
        {"queued_single": list[str], "queued_thread": list[str], "posted": list[dict]}
    """
    queued_single: list[str] = []
    queued_thread: list[str] = []
    posted: list[dict] = []

    # Individual X posts
    for i, tweet_text in enumerate(x_posts):
        item_id = add_to_queue(
            post_urn=post_urn,
            platform="x_post",
            content=tweet_text,
            requires_review=False,
            metadata={"tweet_index": i, "pillar": transform_output.get("CONTENT_CLASSIFICATION", {})},
        )
        queued_single.append(item_id)

        if auto_post_x and is_auto_post_enabled():
            try:
                result = safe_post_tweet(tweet_text)
                mark_posted(item_id, result)
                posted.append(result)
                _log_entry(f"X post {i + 1} posted", result.get("url", "unknown"))
            except Exception as e:
                mark_failed(item_id, str(e))
                _log_entry(f"X post {i + 1} FAILED", str(e))
        else:
            mark_skipped(item_id, "AUTO_POST_X not enabled or auto_post_x=False")

    # X thread
    if x_thread:
        thread_content = json.dumps(x_thread)
        item_id = add_to_queue(
            post_urn=post_urn,
            platform="x_thread",
            content=thread_content,
            requires_review=False,
            metadata={"tweet_count": len(x_thread)},
        )
        queued_thread.append(item_id)

        if auto_post_x and is_auto_post_enabled():
            try:
                results = safe_post_thread(x_thread)
                mark_posted(item_id, {"thread": results})
                posted.extend(results)
                _log_entry("X thread posted", f"{len(results)} tweets — {results[0].get('url', '')}")
            except Exception as e:
                mark_failed(item_id, str(e))
                _log_entry("X thread FAILED", str(e))
        else:
            mark_skipped(item_id, "AUTO_POST_X not enabled")

    return {
        "queued_single": queued_single,
        "queued_thread": queued_thread,
        "posted": posted,
    }


def _queue_beehiiv(post_urn: str, beehiiv_version: Optional[dict], pillar: int) -> Optional[str]:
    """
    Create a Beehiiv draft from the generated newsletter version.
    Always creates as draft — never sends.

    Returns:
        beehiiv_post_id or None
    """
    if not beehiiv_version:
        return None

    subject = beehiiv_version.get("subject_line", "Untitled Newsletter")
    preview_text = beehiiv_version.get("preview_text", "")
    body_md = beehiiv_version.get("body_markdown", "")
    cta_text = beehiiv_version.get("cta_button_text", "Learn More")
    cta_url = beehiiv_version.get("cta_url", "https://mottoappraisal.carrd.co")

    # Add CTA button to body HTML
    body_html = markdown_to_html(body_md)
    cta_html = (
        f'\n\n<div style="text-align:center;margin:32px 0;">'
        f'<a href="{cta_url}" style="background:#1a1a2e;color:#fff;padding:12px 28px;'
        f'border-radius:4px;text-decoration:none;font-weight:600;">{cta_text}</a></div>'
    )
    full_html = body_html + cta_html

    # Queue as a draft record first
    item_id = add_to_queue(
        post_urn=post_urn,
        platform="beehiiv",
        content=json.dumps({"subject": subject, "preview_text": preview_text}),
        requires_review=True,
        metadata={"pillar": pillar, "status": "draft"},
    )

    try:
        result = create_post(
            subject=subject,
            preview_text=preview_text,
            body_html=full_html,
            status="draft",
        )
        mark_posted(item_id, result)
        _log_entry("Beehiiv draft created", f"ID: {result.get('id', 'unknown')} — {subject}")
        return result.get("id")
    except Exception as e:
        mark_failed(item_id, str(e))
        _log_entry("Beehiiv draft FAILED", str(e))
        return None


def _queue_review_item(
    post_urn: str,
    platform: str,
    content: dict | str,
    pillar: int,
    section_name: str,
) -> str:
    """Add a manual review item to the queue. Returns item_id."""
    if isinstance(content, dict):
        content_str = json.dumps(content, indent=2)
    else:
        content_str = str(content)

    item_id = add_to_queue(
        post_urn=post_urn,
        platform=platform,
        content=content_str,
        requires_review=True,
        metadata={"section": section_name, "pillar": pillar},
    )
    _log_entry(f"Manual review queued: {section_name}", f"Item ID: {item_id}")
    return item_id


# ---------------------------------------------------------------------------
# Step 6: Company page post
# ---------------------------------------------------------------------------

def _post_to_company_page(
    post_text: str,
    pillar: int,
    image_path: Optional[str] = None,
) -> Optional[dict]:
    """
    Post a rephrased version to the company page.
    Called automatically after personal LinkedIn post.
    Skipped if POST_TO_COMPANY_PAGE env var is not "true".

    Returns the result dict from post_to_company_page(), or None if skipped/failed.
    """
    if os.environ.get("POST_TO_COMPANY_PAGE", "false").lower() != "true":
        _log("_Company page post skipped (POST_TO_COMPANY_PAGE != true)_")
        return None

    try:
        _log_entry("Company page", "Rephrasing for brand voice...")
        brand_text = rephrase_for_brand(post_text, pillar)

        if not brand_text:
            _log_entry("Company page SKIPPED", "rephrase_for_brand returned empty string")
            return None

        result = post_to_company_page(
            text=brand_text,
            image_urn=None,  # image upload handled separately if needed
        )

        if result.get("success"):
            _log_entry(
                "Company page posted",
                f"URN: {result.get('post_urn', 'unknown')} — "
                f"{result.get('company_page_url', '')}",
            )
        else:
            _log_entry(
                "Company page FAILED",
                f"Status {result.get('status_code', '?')}: {result.get('error', 'unknown error')[:100]}",
            )

        return result

    except Exception as e:
        error_msg = f"Company page post exception: {e}"
        log_str = traceback.format_exc()
        _log(f"❌ {error_msg}")
        return {"success": False, "error": error_msg, "traceback": log_str}


# ---------------------------------------------------------------------------
# Step 7: Community content queueing
# ---------------------------------------------------------------------------

def _queue_community_content(
    post_data: dict,
    transform_output: dict,
    content_class: dict,
) -> dict:
    """
    Add Reddit, LinkedIn group, and Facebook group content to their respective queues.
    Returns counts of items queued per platform.

    Reddit and LinkedIn groups are ALWAYS manual review — never auto-post.
    Facebook managed groups: only auto-post if in confirmed-managed list (currently none).
    """
    post_urn: str = post_data.get("post_urn", "")
    post_text: str = post_data.get("post_text", "")
    pillar: int = int(post_data.get("pillar", 1))

    counts = {
        "reddit": 0,
        "linkedin_groups": 0,
        "facebook_groups": 0,
    }

    # ---- Reddit ----
    _log_section("Step 7a: Reddit Community Queue")
    try:
        reddit_version = transform_output.get("REDDIT_POST_VERSION")
        if content_class.get("subreddit_safe", False) or reddit_version:
            title = ""
            if isinstance(reddit_version, dict):
                title = reddit_version.get("title", "")
            if not title:
                # Derive a short title from the first line of the post
                first_line = post_text.split("\n")[0].strip()
                title = first_line[:280] if first_line else "DFW Appraisal Insight"

            item_ids = queue_for_subreddits(
                post_text=post_text,
                title=title,
                source_post_urn=post_urn,
                pillar=pillar,
                reddit_version=reddit_version if isinstance(reddit_version, dict) else None,
            )
            counts["reddit"] = len(item_ids)
            _log_entry("Reddit items queued", str(counts["reddit"]))
        else:
            _log("_Reddit skipped — subreddit_safe=False and no REDDIT_POST_VERSION_")
    except Exception as e:
        _log(f"❌ Reddit queueing failed: {e}")

    # ---- LinkedIn Groups ----
    _log_section("Step 7b: LinkedIn Groups Queue")
    try:
        li_group_version = transform_output.get("LINKEDIN_GROUP_VERSION")
        group_safe_text = ""
        discussion_question = None

        if isinstance(li_group_version, dict):
            group_safe_text = li_group_version.get("body", li_group_version.get("text", ""))
            discussion_question = li_group_version.get("discussion_question")
        elif isinstance(li_group_version, str):
            group_safe_text = li_group_version

        if group_safe_text or li_group_version:
            item_ids = queue_for_groups(
                post_text=post_text,
                group_safe_version=group_safe_text or post_text,
                source_post_urn=post_urn,
                pillar=pillar,
                discussion_question=discussion_question,
            )
            counts["linkedin_groups"] = len(item_ids)
            _log_entry("LinkedIn group items queued", str(counts["linkedin_groups"]))
        else:
            _log("_LinkedIn groups skipped — no LINKEDIN_GROUP_VERSION generated_")
    except Exception as e:
        _log(f"❌ LinkedIn groups queueing failed: {e}")

    # ---- Facebook Groups ----
    _log_section("Step 7c: Facebook Groups Queue")
    try:
        fb_version = transform_output.get("FACEBOOK_GROUP_VERSION")
        fb_text = ""

        if isinstance(fb_version, dict):
            fb_text = fb_version.get("body", fb_version.get("text", ""))
        elif isinstance(fb_version, str):
            fb_text = fb_version

        final_fb_text = fb_text or post_text

        # Build a list of relevant group entries and queue each
        from tools.facebook_groups import RELEVANT_GROUP_TYPES, queue_for_manual_review as _fb_queue

        fb_item_ids: list[str] = []
        for group_name in RELEVANT_GROUP_TYPES:
            encoded_name = group_name.replace(" ", "%20")
            group_url = f"https://www.facebook.com/search/groups/?q={encoded_name}"
            item_id = _fb_queue(
                group_name=group_name,
                group_url=group_url,
                post_text=final_fb_text,
                source_post_urn=post_urn,
                pillar=pillar,
            )
            if item_id:
                fb_item_ids.append(item_id)

        counts["facebook_groups"] = len(fb_item_ids)
        _log_entry("Facebook group items queued", str(counts["facebook_groups"]))

    except Exception as e:
        _log(f"❌ Facebook groups queueing failed: {e}")

    return counts


# ---------------------------------------------------------------------------
# Main orchestrator
# ---------------------------------------------------------------------------

def distribute(post_data: dict, auto_post_x: bool = False) -> dict:
    """
    Full distribution pipeline for one piece of content.

    Args:
        post_data: {
            post_urn: str,      — unique identifier for the LinkedIn post
            post_text: str,     — full text of the post
            pillar: int,        — content pillar (1–6)
            format_type: str,   — "educational" | "data" | "opinion" | "promo"
            char_count: int,    — character count (optional, computed if absent)
            published_at: str,  — ISO8601 timestamp of original post
        }
        auto_post_x: bool — if True AND AUTO_POST_X env var is "true", post to X immediately.
                            Both conditions must be met. Defaults to False.

    Returns:
        Summary dict of what was queued, posted, and flagged for review.
    """
    post_urn: str = post_data.get("post_urn", f"urn:li:activity:{int(time.time())}")
    post_text: str = post_data.get("post_text", "")
    pillar: int = int(post_data.get("pillar", 1))

    if not post_text:
        raise ValueError("post_data must include 'post_text'.")

    _init_log_run(post_urn, pillar)

    summary: dict = {
        "post_urn": post_urn,
        "pillar": pillar,
        "run_at": _now(),
        "classification": {},
        "transform_cost": {},
        "queued": {
            "x_posts": [],
            "x_thread": [],
            "beehiiv_draft_id": None,
            "review_items": [],
            "community": {
                "reddit": 0,
                "linkedin_groups": 0,
                "facebook_groups": 0,
            },
        },
        "posted": [],
        "company_page": None,
        "errors": [],
        "results_file": None,
    }

    # ------------------------------------------------------------------
    # Step 1: Classify
    # ------------------------------------------------------------------
    _log_section("Step 1: Classification")
    try:
        content_class = classify(post_data)
        summary["classification"] = content_class
        _log_entry("Promotion risk", content_class["promotion_risk_level"])
        _log_entry("Public feed safe", str(content_class["public_feed_safe"]))
        _log_entry("Subreddit safe", str(content_class["subreddit_safe"]))
        _log_entry("Long form safe", str(content_class["long_form_safe"]))
        _log_entry("Recommended platforms", ", ".join(content_class["recommended_platforms"]))
    except Exception as e:
        error_msg = f"Classification failed: {e}"
        summary["errors"].append(error_msg)
        _log(f"❌ {error_msg}")
        return summary

    # ------------------------------------------------------------------
    # Step 2: Transform
    # ------------------------------------------------------------------
    _log_section("Step 2: Transform (Claude generation)")
    try:
        transform_output = transform(post_data, content_class, pillar)
        cost_info = transform_output.get("cost_tracking", {})
        summary["transform_cost"] = {
            "total_estimated_usd": cost_info.get("total_estimated_cost_usd", 0),
            "total_input_tokens": cost_info.get("total_input_tokens", 0),
            "total_output_tokens": cost_info.get("total_output_tokens", 0),
            "model": cost_info.get("model", "unknown"),
        }
        _log_entry(
            "Transform cost",
            f"${cost_info.get('total_estimated_cost_usd', 0):.4f} "
            f"({cost_info.get('total_input_tokens', 0)} input / "
            f"{cost_info.get('total_output_tokens', 0)} output tokens)",
        )
    except Exception as e:
        error_msg = f"Transform failed: {e}\n{traceback.format_exc()}"
        summary["errors"].append(error_msg)
        _log(f"❌ {error_msg}")
        return summary

    # ------------------------------------------------------------------
    # Step 3: Queue X posts
    # ------------------------------------------------------------------
    _log_section("Step 3: X (Twitter) Distribution")
    x_posts: list[str] = transform_output.get("X_POSTS") or []
    x_thread: list[str] = transform_output.get("X_THREAD") or []

    if x_posts or x_thread:
        try:
            x_result = _queue_x_posts(
                post_urn, x_posts, x_thread, auto_post_x, transform_output
            )
            summary["queued"]["x_posts"] = x_result["queued_single"]
            summary["queued"]["x_thread"] = x_result["queued_thread"]
            summary["posted"].extend(x_result["posted"])
            _log_entry("X posts queued", str(len(x_result["queued_single"])))
            _log_entry("X thread queued", "Yes" if x_result["queued_thread"] else "No")
            _log_entry("X posts auto-posted", str(len(x_result["posted"])))
        except Exception as e:
            error_msg = f"X queueing failed: {e}"
            summary["errors"].append(error_msg)
            _log(f"❌ {error_msg}")
    else:
        _log("_No X content generated (public_feed_safe=False)_")

    # ------------------------------------------------------------------
    # Step 4: Queue Beehiiv draft
    # ------------------------------------------------------------------
    _log_section("Step 4: Beehiiv Newsletter Draft")
    beehiiv_version = transform_output.get("BEEHIIV_VERSION")
    if beehiiv_version:
        try:
            draft_id = _queue_beehiiv(post_urn, beehiiv_version, pillar)
            summary["queued"]["beehiiv_draft_id"] = draft_id
            if draft_id:
                _log_entry("Beehiiv draft created", draft_id)
            else:
                _log("_Beehiiv draft creation failed — check errors_")
        except Exception as e:
            error_msg = f"Beehiiv failed: {e}"
            summary["errors"].append(error_msg)
            _log(f"❌ {error_msg}")
    else:
        _log("_No Beehiiv content generated (long_form_safe=False and outreach_snippet_safe=False)_")

    # ------------------------------------------------------------------
    # Step 5: Manual review queue (Reddit, Facebook, LinkedIn groups)
    # ------------------------------------------------------------------
    _log_section("Step 5: Manual Review Queue")

    review_items: list[str] = []

    # LinkedIn Group
    if transform_output.get("LINKEDIN_GROUP_VERSION"):
        item_id = _queue_review_item(
            post_urn, "linkedin_group",
            transform_output["LINKEDIN_GROUP_VERSION"],
            pillar, "LINKEDIN_GROUP_VERSION"
        )
        review_items.append(item_id)

    # Facebook Group
    if transform_output.get("FACEBOOK_GROUP_VERSION"):
        item_id = _queue_review_item(
            post_urn, "facebook_group",
            transform_output["FACEBOOK_GROUP_VERSION"],
            pillar, "FACEBOOK_GROUP_VERSION"
        )
        review_items.append(item_id)

    # Reddit Post
    if transform_output.get("REDDIT_POST_VERSION"):
        item_id = _queue_review_item(
            post_urn, "reddit",
            transform_output["REDDIT_POST_VERSION"],
            pillar, "REDDIT_POST_VERSION"
        )
        review_items.append(item_id)

    # Reddit Comment
    if transform_output.get("REDDIT_COMMENT_VERSION"):
        item_id = _queue_review_item(
            post_urn, "reddit",
            transform_output["REDDIT_COMMENT_VERSION"],
            pillar, "REDDIT_COMMENT_VERSION"
        )
        review_items.append(item_id)

    # Medium / Substack / LinkedIn Article (long form — always manual)
    for section, platform in [
        ("MEDIUM_VERSION", "medium"),
        ("SUBSTACK_VERSION", "substack"),
        ("LINKEDIN_ARTICLE_VERSION", "linkedin"),
    ]:
        if transform_output.get(section):
            item_id = _queue_review_item(
                post_urn, platform,
                transform_output[section],
                pillar, section
            )
            review_items.append(item_id)

    summary["queued"]["review_items"] = review_items
    _log_entry("Manual review items queued", str(len(review_items)))

    # ------------------------------------------------------------------
    # Step 6: Company page post
    # ------------------------------------------------------------------
    _log_section("Step 6: LinkedIn Company Page Post")
    try:
        company_result = _post_to_company_page(post_text, pillar)
        summary["company_page"] = company_result
        if company_result and company_result.get("success"):
            summary["posted"].append(company_result)
    except Exception as e:
        error_msg = f"Company page step failed: {e}"
        summary["errors"].append(error_msg)
        _log(f"❌ {error_msg}")

    # ------------------------------------------------------------------
    # Step 7: Queue community content (Reddit, LinkedIn groups, FB groups)
    # ------------------------------------------------------------------
    _log_section("Step 7: Community Content Queuing")
    try:
        community_counts = _queue_community_content(post_data, transform_output, content_class)
        summary["queued"]["community"] = community_counts
        _log_entry(
            "Community totals",
            f"Reddit: {community_counts['reddit']} | "
            f"LI Groups: {community_counts['linkedin_groups']} | "
            f"FB Groups: {community_counts['facebook_groups']}",
        )
    except Exception as e:
        error_msg = f"Community content queueing failed: {e}\n{traceback.format_exc()}"
        summary["errors"].append(error_msg)
        _log(f"❌ {error_msg}")

    # ------------------------------------------------------------------
    # Step 8: Save full results
    # ------------------------------------------------------------------
    _log_section("Step 8: Results Persistence")

    full_results = {
        "post_data": post_data,
        "summary": summary,
        "transform_output": transform_output,
    }

    try:
        results_path = _save_results(post_urn, full_results)
        summary["results_file"] = str(results_path)
        _log_entry("Results saved", str(results_path))
    except Exception as e:
        _log(f"⚠️  Failed to save results file: {e}")

    # Queue stats
    try:
        stats = get_stats()
        _log_entry("Queue total", str(stats["status_counts"]["total"]))
        _log_entry("Pending", str(stats["status_counts"]["pending"]))
        _log_entry("Review required", str(stats["status_counts"]["review_required"]))
    except Exception:
        pass

    # Final summary log
    community = summary["queued"]["community"]
    _log("\n---")
    _log(f"**Run complete**: {_now()}")
    _log(
        f"**Cost**: ${summary['transform_cost'].get('total_estimated_usd', 0):.4f} | "
        f"**Errors**: {len(summary['errors'])} | "
        f"**Review items**: {len(review_items)} | "
        f"**Community queued**: Reddit={community['reddit']}, "
        f"LI Groups={community['linkedin_groups']}, "
        f"FB Groups={community['facebook_groups']}"
    )
    _log("\n---\n")

    return summary


# ---------------------------------------------------------------------------
# CLI entrypoint
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Motto Appraisal — Content Distribution Engine"
    )
    parser.add_argument(
        "--post-file",
        type=str,
        required=False,
        help="Path to a JSON file containing post_data dict",
    )
    parser.add_argument(
        "--auto-post-x",
        action="store_true",
        default=False,
        help="Enable X auto-posting (also requires AUTO_POST_X=true env var)",
    )
    parser.add_argument(
        "--pillar",
        type=int,
        default=1,
        help="Content pillar (1–6)",
    )
    parser.add_argument(
        "--demo",
        action="store_true",
        help="Run with a built-in demo post (no file required)",
    )
    args = parser.parse_args()

    if args.demo:
        post_data = {
            "post_urn": f"urn:li:activity:demo_{int(time.time())}",
            "post_text": (
                "AVM said $420k. My appraisal came in at $387k.\n\n"
                "The delta? A 450 sq ft unpermitted addition with mismatched flooring "
                "that Zillow's model will never catch.\n\n"
                "AVMs read square footage and zip code. They don't read condition, "
                "effective age, or deferred maintenance.\n\n"
                "That 8% gap costs buyers real money and lenders real risk.\n\n"
                "If you're underwriting DSCR loans in DFW, here's what to watch for:\n"
                "• Permitted vs unpermitted additions\n"
                "• Pool condition adjustments\n"
                "• Functional obsolescence from dated floor plans\n\n"
                "AVM confidence scores are not appraiser sign-offs."
            ),
            "pillar": args.pillar,
            "format_type": "educational",
            "char_count": 580,
            "published_at": _now(),
        }
    elif args.post_file:
        with open(args.post_file) as f:
            post_data = json.load(f)
    else:
        parser.print_help()
        sys.exit(0)

    print(f"Starting distribution for post: {post_data['post_urn']}")
    print(f"Pillar: {post_data.get('pillar', 1)} | AUTO_POST_X: {is_auto_post_enabled()}")
    print(f"POST_TO_COMPANY_PAGE: {os.environ.get('POST_TO_COMPANY_PAGE', 'false')}")
    print("─" * 60)

    result = distribute(post_data, auto_post_x=args.auto_post_x)

    community = result["queued"].get("community", {})
    print("\n✓ Distribution complete")
    print(f"  Cost: ${result['transform_cost'].get('total_estimated_usd', 0):.4f}")
    print(f"  Review items: {len(result['queued']['review_items'])}")
    print(f"  Community queued: Reddit={community.get('reddit', 0)}, LI Groups={community.get('linkedin_groups', 0)}, FB Groups={community.get('facebook_groups', 0)}")
    print(f"  Company page: {'posted' if result.get('company_page', {}) and result['company_page'].get('success') else 'skipped/failed'}")
    print(f"  Posted: {len(result['posted'])}")
    print(f"  Errors: {len(result['errors'])}")
    print(f"  Results: {result.get('results_file', 'not saved')}")

    if result["errors"]:
        print("\nErrors:")
        for err in result["errors"]:
            print(f"  - {err}")
